--!Type(Module)

local openingQuestions = {
    "Hi, how are you today?",
    "Hey, what's your name?",
    "Hey, how old are you?",
    "Hey nice to meet you, how is it going?",
    "Hi, which city are you from?",
    "Hey, how's your day going so far?"
}

local questions = {
    -- What
    "What's your biggest pet peeve",
    "What can easily make you angry?",
    "What's the most difficult task you have ever completed?",
    "What habit would you most like to change?",
    "What's one life hack you've discovered that helped you a lot",
    "What's the weirdest thing you've seen happened to someone or yourself?",
    "What's one thing on your bucket list?",
    "What's your favorite childhood cartoon?",
    "What's your favorite thing to do with friends?",
    "What's something you've always wanted to learn or try?",
    "What's your all time favorite book",
    "What book are you reading at the moment?",
    "What's your favorite book genre?",
    "What's your all time favorite movie?",
    "What's your favorite movie genre?",
    "What's your all time favourite TV Show?",
    "What kind of music do you like?",
    "What is your current favorite app on your phone?",
    "What is your favorite tabletop game?",
    "What is your favorite mobile game?",
    "What is your favorite pc game?",
    "What's the most adventurous thing you've ever done?",
    "What's the most reckless thing you've ever done?",
    "What's the most interesting place you've visited?",
    "What's your favorite type of cuisine?",
    "What's the weirdest food you've ever tried?",
    "What's your favorite food?",
    "What's your favorite ice cream flavor?",
    "What's your favorite type of dessert?",
    "What's your favorite thing to cook or bake?",
    "What's the best thing that you can cook?",
    "What's your favorite fruit?",
    "What's the funniest joke you've heard",
    "What's your dream job?",
    "What's your favorite sport?",
    "What's your favorite outdoor activity?",
    "What's the most important lesson you've learned from a past relationship?",
    "What interests you most in a person?",
    "What does your ideal home look like, apart from the essentails?",
    "What's your favorite color?",
    "What was your first job like?",
    "What's the funniest pick-up line someone has used on you?",
    "What's the most creative pick-up line you've ever heard?",
    "What pick-up line would you use if you had to impress someone right now?",

    -- Which
    "Which is the last tv show you watched?",
    "Which is the last movie you watched?",
    "Which is the last book you read?",
    "Which are your top three music artists",
    "Which do you prefer, mountains or beaches?",
    "Which do you prefer, summers or winters?",
    "Which do you prefer, coffee or tea?",
    "Which do your prefer, vanilla or chocolate?",
    "Which do you prefer, long-term relationship or short-term flings?",
    "Which do you prefer, cats or dogs?",
    "Which countries have you travelled to?",
    "Which is the last documentary you watched?",
    
    -- Where
    "Where do you live?",
    "Where do you see yourself in five years?",
    "Where would you go on your next vacation?",
    "Where would you go on your dream vacation?",
    "Where did you go on your last vacation?",
    "Where would you like to take someone on a first date?",

    -- How
    "How is the weather where you live?",
    "How do you de-stress?",
    "How many languages do you speak?",
    "How do you spend your weekends?",
    "How do you stay positive in tough times?",
    "How do you like to spend your free time?",
    "How do you stay optimistic?",
    "How do you handle peer pressure?",

    -- Do
    "Do you prefer to drive or sit in the passenger seat?",
    "Do you prefer mornings or evenings?",
    "Do you enjoy listening to podcasts? If yes, which ones?",
    "Do you like to call or text?",
    "Do you play any musical instrument?",
    "Do you follow politics?",
    "Do you believe in love at first sight?",
    "Do you have any pets?",
    "Do you work and if so what is your profression?",
    "Do you like working from home or the office?",
    "Do you believe in supernatural things?",
    "Do you like to dance?",
    "Do you enjoy playing video games?",
    "Do you believe in mircales?",
    "Do you believe in climate change?",
    "Do you prefer reading fiction or non-fiction?",
    "Do you prefer to work independently or in a team?",
    "Do you like to go on road trips?",
    "Do you believe in traditional gender roles?",
    "Do you think pick-up lines actually work?",
    "Do you have a travel hack for making trips more enjoyable or efficient?",
    "Do you have a fitness hack for staying in shape and healthy?",

    -- Have
    "Have you ever met anyone famous?",
    "Have you ever won a contest or competition?",
    "Have you ever volunteered for a community service?",
    "Have you ever traveled to another country?",
    "Have you ever tried an extreme sport?",
    "Have you ever been on a road trip?",
    "Have you ever learned to play a musical instrument?",
    "Have you ever had a pet?",
    "Have you ever performed on stage?",
    "Have you ever had a paranormal experience?",
    "Have you ever experienced a natural disaster?",
    "Have you ever been scuba diving or snorkeling?",
    "Have you ever done sky diving?",
    "Have you ever tried meditation or yoga?",
    "Have you ever participated in a protest or march?",
    "Have you ever been to a theme park?",
    "Have you ever hosted a party or event?",
    "Have you ever climbed a mountain or gone hiking?",
    "Have you ever written for a newspaper or magazine?",
    "Have you ever visited a different continent?",
    "Have you ever started a startup or business venture?",
    "Have you ever been lost or trapped?",
    "Have you ever participated in a talent show?",
    "Have you ever made a bucket list?",
    "Have you ever done something outside your comfort zone?",
    "Have you ever sung karaoke in front of a crowd?",
    "Have you ever made a major career change?",
    "Have you ever used a pick-up line yourself? How did it go?",
    
    -- If
    "If you could eliminate one thing from your daily routine forever, what would it be?",
    "If you could live in any city in the world, where would you live?",
    "If you could be any fictional character, who would you be?",
    "If you were a superhero, what would your superpower be?",
    "If you could be any person for a day, who would you choose and why?",
    "If you won the lottery how would you spend it?",
    "If I come to your house, what would you cook for me?",
    "If you had the option to be on the first human mission to mars, would you go?",
    "If you could meet any living person, who would it be?",
    "If you could have a superpower for a day, what would it be?",
    "If you could visit any planet safely, which one would you choose?",
    "If you could invent a holiday, what would it be?",
    "If you could be an expert in any field, what would it be?",
    "If you could visit any fictional world, where would you go?",
    "If you could meet any historical figure, who would you choose?",
    "If you could change one thing about the world, what would it be?",
    "If you could buy one thing, no matter the price, what would you buy?",
    "If you had to give up one of your five senses, which one would it be?",
    "If you could be famous for one thing, what would it be?",
    "If you could visit any historical era for a vacation, which place and time would you choose?",
    "If you could instantly become a professional at any sport, which one would you pick?",
    "If you could know the answer to any question, what question would you ask?",
    "If you could redo one decision in your life, what would it be?",
    "If you could invent anything, what would it be?",
    "If you could play any musical instrument perfectly, which one would you choose?",
    "If you could be the CEO of any company, which one would you choose?",
    "If you could own any car, which one would it be?",
    "If you could go back and change one moment in history, what would it be?",
    "If you could only wear one color for the rest of your life, what would it be?",
    "If you could only eat one type of cuisine for the rest of your life, what would it be?",
    "If you had the opporutinity to make a theme park, what would it be like?",
    "If you could go on a road trip anywhere with anyone, who would you take and where?",
    "If you could live in a different country for a year, where would you go?",
    "If you could create a new holiday, what would it celebrate?",

    -- Who
    "Who would you want to be stuck with on an island?",
    "Who is your favorite fictional character?",
    "Who is your favorite author?",
    "Who do you think has the most interesting job?",
    "Who do you think is the best leader in history?",
    "Who is your favorite actor or actress?",
    "Who would you like to interview if you were a journalist?",
    "Who is your favorite comedian?",
    "Who do you think is the most philanthropic person?",

    -- Can
    "Can you share an interesting quote or saying?",
    "Can you recommend me a great movie?",
    "Can you recommend me a great tv show?",
    "Can you recommend me a great book?",
    "Can you share a pick-up line that actually worked on you?",
    "Can you share a productivity tip?",

    -- Would
    "Would you rather go scuba diving or skydiving?",
    "Would you rather time travel to the past or to the future",
    "Would you rather shop online or at the mall?",
    "Would you rather have a partner with a great sense of humor or a partner who is super attractive?",
    "Would you rather be single or in a relationship",
    "Would you rather be able to breathe underwater or fly?",
    "Would you rather live in a world with no crime or no privacy?",
    "Would you rather lose all your money or your memories",
    "Would you rather be an average person in the present or a king of a large country 2500 years ago?",
    "Would you rather have an easy job working for someone else or work for yourself but work incredibly hard?",
    "Would you rather never be able to eat meat or never be able to eat vegetables?",
    "Would you rather find your true love or a suitcase with five million dollars inside?",
    "Would you rather live without the internet or live without air conditioning and heating?",
    "Would you rather never be stuck in traffic again or never get another cold?",
    "Would you rather be forced to dance or sing along every time you heard music?",
    "Would you rather go to a water park or a dry park?"
}

function GetOpeningQuestions()
    return openingQuestions
end

function GetQuestions()
    return questions
end