/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/AudioManager")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class AudioManager : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "f40bfb5354f26ce4daf5670d0e9d6846";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.AudioSource m_move = default;
        [SerializeField] public UnityEngine.AudioSource m_diceRoll = default;
        [SerializeField] public UnityEngine.AudioSource m_click = default;
        [SerializeField] public UnityEngine.AudioSource m_cardDraw = default;
        [SerializeField] public UnityEngine.AudioSource m_zap = default;
        [SerializeField] public UnityEngine.AudioSource m_nos = default;
        [SerializeField] public UnityEngine.AudioSource m_hit = default;
        [SerializeField] public UnityEngine.AudioSource m_raceStart = default;
        [SerializeField] public UnityEngine.AudioSource m_disconnect = default;
        [SerializeField] public UnityEngine.AudioSource m_resultNotify = default;
        [SerializeField] public UnityEngine.AudioSource m_honk = default;
        [SerializeField] public UnityEngine.AudioSource m_anomaly = default;
        [SerializeField] public UnityEngine.AudioSource m_teleport = default;
        [SerializeField] public UnityEngine.AudioSource m_damage = default;
        [SerializeField] public UnityEngine.AudioSource m_checkpoint = default;
        [SerializeField] public UnityEngine.AudioSource m_upgrade = default;
        [SerializeField] public UnityEngine.AudioSource m_flame = default;
        [SerializeField] public UnityEngine.AudioSource m_shield = default;
        [SerializeField] public UnityEngine.AudioSource m_hook = default;
        [SerializeField] public UnityEngine.AudioSource m_laser = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_move),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_diceRoll),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_click),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_cardDraw),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_zap),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_nos),
                CreateSerializedProperty(_script.GetPropertyAt(6), m_hit),
                CreateSerializedProperty(_script.GetPropertyAt(7), m_raceStart),
                CreateSerializedProperty(_script.GetPropertyAt(8), m_disconnect),
                CreateSerializedProperty(_script.GetPropertyAt(9), m_resultNotify),
                CreateSerializedProperty(_script.GetPropertyAt(10), m_honk),
                CreateSerializedProperty(_script.GetPropertyAt(11), m_anomaly),
                CreateSerializedProperty(_script.GetPropertyAt(12), m_teleport),
                CreateSerializedProperty(_script.GetPropertyAt(13), m_damage),
                CreateSerializedProperty(_script.GetPropertyAt(14), m_checkpoint),
                CreateSerializedProperty(_script.GetPropertyAt(15), m_upgrade),
                CreateSerializedProperty(_script.GetPropertyAt(16), m_flame),
                CreateSerializedProperty(_script.GetPropertyAt(17), m_shield),
                CreateSerializedProperty(_script.GetPropertyAt(18), m_hook),
                CreateSerializedProperty(_script.GetPropertyAt(19), m_laser),
            };
        }
    }
}

#endif
