/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PrivateChat")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class PrivateChat : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "8d108b04dccf8ef4c80548fb8eb28571";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.Boolean m_enableDevMode = false;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_enableDevMode),
            };
        }
    }
}

#endif
