/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/RaceGame")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class RaceGame : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "a1fab168d5f4ef540b8f3cd1af3cf18b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_boardGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_playerHudGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_cardManagerGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_audioManagerGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_botGameObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_boardGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_playerHudGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_cardManagerGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_audioManagerGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_botGameObject),
            };
        }
    }
}

#endif
