/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/References")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class References : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "23af509a3f3491f43bf810d021751c7a";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_gameUIGameObject = default;
        [SerializeField] public UnityEngine.GameObject m_seatManagerGameObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_gameUIGameObject),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_seatManagerGameObject),
            };
        }
    }
}

#endif
